export const FEATURE_ORDER = [
    "total_pemasukan",
    "total_pengeluaran",
    "total_tabungan_investasi",
    "saldo_akhir_estimasi",
    "rasio_pengeluaran",
    "rasio_tabungan_investasi",
    "jumlah_transaksi",
    "rata_rata_nominal",
    "median_nominal",
    "max_nominal",
    "rasio_makanan",
    "rasio_belanja_fashion",
    "rasio_hiburan",
    "rasio_kebutuhan_pokok",
    "jumlah_transaksi_awal_bulan",
    "jumlah_transaksi_akhir_bulan",
    "total_pengeluaran_awal_bulan",
    "total_pengeluaran_akhir_bulan",
    "rasio_pengeluaran_akhir_bulan",
    "rasio_transaksi_akhir_bulan",
    "total_nominal",

    "belanja",
    "bonus",
    "fashion",
    "gaji",
    "hiburan",
    "investasi",
    "kesehatan",
    "lainnya",
    "makanan dan minuman",
    "pendidikan",
    "tabungan",
    "tagihan",
    "transportasi",

    "count_belanja",
    "count_bonus",
    "count_fashion",
    "count_gaji",
    "count_hiburan",
    "count_investasi",
    "count_kesehatan",
    "count_lainnya",
    "count_makanan dan minuman",
    "count_pendidikan",
    "count_tabungan",
    "count_tagihan",
    "count_transportasi"
]