/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fbf8fa",
        "secondary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#3c475a",
        "outline-variant": "#c5c6cd",
        "on-secondary-container": "#684000",
        "error-container": "#ffdad6",
        "surface-container": "#f0edef",
        "on-tertiary-container": "#00a472",
        "on-primary-container": "#8590a6",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffddb8",
        "secondary-container": "#fea619",
        "on-secondary-fixed-variant": "#653e00",
        "primary-fixed-dim": "#bcc7de",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#bcc7de",
        "surface-container-highest": "#e4e2e3",
        "on-error": "#ffffff",
        "background": "#fbf8fa",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e4e2e3",
        "inverse-surface": "#303032",
        "on-secondary-fixed": "#2a1700",
        "on-surface-variant": "#45474c",
        "on-surface": "#1b1b1d",
        "inverse-on-surface": "#f3f0f2",
        "on-primary-fixed": "#111c2d",
        "surface-container-high": "#eae7e9",
        "tertiary-container": "#00301e",
        "primary-container": "#1e293b",
        "on-primary": "#ffffff",
        "primary": "#091426",
        "outline": "#75777d",
        "surface-container-low": "#f5f3f4",
        "tertiary-fixed": "#6ffbbe",
        "surface-tint": "#545f73",
        "primary-fixed": "#d8e3fb",
        "surface-bright": "#fbf8fa",
        "secondary": "#855300",
        "on-tertiary-fixed": "#002113",
        "on-background": "#1b1b1d",
        "surface-dim": "#dcd9db",
        "tertiary": "#00190e",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "unit": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}
